2.0.0
ktsstudio/create-mediaproject pull request #20
Opened 2022-09-13 15:07 UTC by n-merkulova

- **добавлен режим разработки шаблонов** ([тут](https://github.com/ktsstudio/create-mediaproject/pull/9) описано, как он работает) ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/commits/9f28f509b5fc3770bbd2c2adb1d9088654aedd99))
- файл .gitignore теперь генерируется на лету, а не копируется с остальными файлами проектов ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-66f2a78cef854525bae1584d36676f1400a9092d3510062998496576c8dc4ef3))
- vk-mini-app:
  - отрефакторены стили в src/styles/styles.scss, добавлены комментарии ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-1247722b0b414c60c8465dd6eaf222bb22770f237eac9fa2e10e2ae013171f48))
  - **поднята версия react-router (с 5 на 6)**
  - **изменена логика работы с историей** ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/commits/ce889afd7e4da430a80c9daee29209caf2eea490)):
    - удалены хуки useVKHistory и useVKLocation, работа с историей перенесена в стор HistoryStore
    - добавлена поддержка swipeback (в HistoryStore создается кастомная история, которая передается во View внутри компонента Root)
  - в ConfigProvider в App передается webviewType ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-c8cc26b19bdd1f375daeed8122865a91d0ac0aa0320f23667a0dfb78434a867a))
  - удален компонент Container
  - изменен компонент VKPanel ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-2eed1038e7002f68726debe6f75bd102bc21b147fc3b8eebae20ba7a19784a5d))
  - добавлен вызов компонента AppRoot в pages/Root ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-93c16f7f633b6c6b0573359bd30925b6f5edf054a5d71e3b6ca32c13e4baba01))
  - добавлен хук useScroll для прокрутки страницы ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-b23cdf06b5ccbe6e19a90e57e6f45edc928cfcaac2fd56b8f8d6c9898056f647))
  - исправлен [issue с copy-webpack-plugin](https://github.com/ktsstudio/create-mediaproject/issues/22)
  - изменена структура сборки для ОДР, теперь в ней файлы разделены по папкам css/fonts/img/js, так же как в обычной сборке ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/commits/a4aede7b2deca735e4b76d44998689cdd5275105))
- все шаблоны:
  - **изменен процесс загрузки проекта**:
    - добавлена модель AppStateModel, экземпляр которой создается в RootStore ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-e66c294ee0c7aeef34b0d01c19242cd8acebf82e5043d27092d2ea75af367924))
    - глобальные сторы внутри RootStore создаются в методе init стора RootStore. там же проходит авторизация ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-60795e0b8e3abaebd85568dc76c80112e12edd9c9bb9eb0125fb5ab0fe328ec6))
    - добавлен хук useAppLoad для контроля состояния приложения (если изменить состояние приложения в rootStore.appState на notLoaded, приложение будет полностью перезагружено) ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-b5f08b57edd0212ca5a44e63ba9ba19fb6ee03636d3f9729213c994e6e57dba3))
    - удален компонент Splash, загрузка и ошибка загрузки приложения обрабатываются в компоненте Root ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-93c16f7f633b6c6b0573359bd30925b6f5edf054a5d71e3b6ca32c13e4baba01))
  - изменена структура файлов в src/store:
    - глобальные сторы лежат в src/store/globals ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-e56cf41a478798fac167d17cadaf64e7456eab3e135aa24cdb2ae9cfbc44e15d))
    - локальные сторы лежат в src/store/locals
    - модели лежат в src/store/models, добавлена модель AppStateModel ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-ef7c9dbfdb9539dff9416c7dfe428f989cf8492500b5db8fed7a9fa5efba4469))
    - интерфейсы лежат в src/store/interfaces, добавлен интерфейс ILocalStore ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-78af34939b1f23d5f2afdb3649f6622653cd10a684bd63a6fc0475d0c7f75019))
    - хуки лежат в src/store/hooks, добавлены хуки useLocalStore и useAppLoad ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-eb2283440e01e204a77ecbd8b1bf4400a761e0dcd3e0ca43c5000c698c8cd047))
  - добавлен плагин для минификации css - css-minimizer-webpack-plugin ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-c88f575c971cc40e10a1e0dd209178888cadb2e2590e8c9d7311f147bca24cec))
  - в author в package.json теперь указывается KTS, а не KTS Studio
  - добавлен файл .editorconfig ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-77f1737fc3f9cd97eacdc4264fa929824d6694712790d5b3839e8dbfb7230abb))
  - **обновлен конфиг eslint - теперь в нем сильно больше правил, касающихся форматирования кода** ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-41ebcb99380901faf5823eb07bf683b4aff8756547a0612e4e4c2de908f2680f))
  - синхронизированы урлы апи в файлах `gitlab-ci.yml` и `webpack.config.js`, теперь везде одинаковый формат `<%= projectName %>.ktsdev.ru` ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-7aea4fbfc59e6c1fe9ddc34fa141be199eacc680f5b3f0f526007939ee58208d))
  - исправлен конфиг prettier - теперь в файлах со стилями используются двойные кавычки, а не одинарные ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-1d33b157026c53cc5c0d8d6fd20584d02f253fa4bbd1205584375f7552d1907b))
  - **добавлен stylelint** ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-834b233f49f1c8ffd206b43811d4c4ddb64a5d3029ffe40e92bf3c26baa9a452))
  - доработан babel.config.js - добавлены плагины, изменено поле targets, изменен формат css-модулей на более читабельный ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-e6f1d7978c4d66eb216c5bbd0c82550995ac53504e70d44f0df0b2f412ead80b))
  - **добавлены новые скрипты в package.template.json** ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-12518d6d4eb184e3c0fae9060df6a14001c553c21b062d41dc6d16e195a39fbb)):
    - `stylelint` -- прогнать стили через линтер
    - `stylelint:fix` -- прогнать стили через линтер и попробовать исправить ошибки
    - `lint` -- прогнать файлы с кодом через линтер без исправления ошибок
    - `format` -- прогнать файлы через stylelint, eslint с исправлением ошибок, плюс прогнать prettier
  - **переименованы скрипты в package.template.json** ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-12518d6d4eb184e3c0fae9060df6a14001c553c21b062d41dc6d16e195a39fbb)):
    - `lint-fix` -> `lint:fix`
    - `ts-check` -> `tsc:check`
    - `codestyle-fix` -> `codestyle:fix`
  - добавлена секция browserslist в package.template.json ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-12518d6d4eb184e3c0fae9060df6a14001c553c21b062d41dc6d16e195a39fbb))
  - поднята версия библиотеки @ktsstudio/mediaproject-stores до 2.1.1
  - **изменен нейминг файлов с css-модулями** - вместо _.modules.css теперь _.module.css (как во всем фронтенде)
  - исправлен [issue с ErrorBoundary](https://github.com/ktsstudio/create-mediaproject/issues/11)
  - отрефакторен конфиг вебпака - файл побит на секции, исправлены небольшие баги ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/files#diff-c88f575c971cc40e10a1e0dd209178888cadb2e2590e8c9d7311f147bca24cec))
  - eruda теперь импортируется динамически, если `window.is_dev === true`
  - компонент приложения App обернут в `<React.StrictMode>`
  - исправлен [issue c PreloadPlugin](https://github.com/ktsstudio/create-mediaproject/issues/13)
  - **изменена логика отправки sourcemap в sentry:** ([diff](https://github.com/ktsstudio/create-mediaproject/pull/20/commits/82db391f724c50fd33620d22b54afe78ffa72e3a))
    - название релиза генерируется не по version из package.json, а по названию коммита
    - сорсмапы отп [...]

2022-09-14 14:21 UTC, natalya-z approved these changes

2022-09-14 14:21 UTC, natalya-z commented on src/templates/vk-mini-app/src/App.tsx
> +      <AdaptivityProvider>
вроде была проблема на клипперах когда-то, что если если не прописать явно viewWidth для дестопа, то на десктопе все vk ui компоненты будут выглядеть как в мобильной версии, а не как должны в десктопной. Например:
```
import { ViewWidth } from '@vkontakte/vkui';
 <AdaptivityProvider viewWidth={window.is_mobile ? undefined : ViewWidth.DESKTOP}>
```

2022-09-14 14:21 UTC, natalya-z commented on src/templates/vk-mini-app/src/components/special/VKPanel/VKPanel.module.scss
> +  .background {
скорее всего не сработает, если использовать Epic, так как у этого компонента отдельный padding-bottom для таббара. и background растянется до этого padding-bottom, то padding-bottom не заполнит. может быть стоит это подписать. Например:
![Uploading Снимок экрана 2022-09-14 в 17.03.29.png…]()

2022-09-14 14:21 UTC, natalya-z commented on src/templates/vk-mini-app/src/styles/fonts/VKSansDisplay/fonts.scss
> +  font-family: "VK Sans Display";
может нам не хранить у себя этот шрифт, а использовать: import '@vkontakte/vkui/dist/fonts.css' 
https://vkcom.github.io/VKUI/#/Fonts
но я не знаю сработает ли расширение .css и тогда надо менять прелоадер, настроенный в вебпаке. + пример работы с шрифтами не хочется терять

2022-09-14 16:08 UTC, AliceSitedge requested changes

2022-09-16 14:20 UTC, n-merkulova commented on src/templates/vk-mini-app/src/App.tsx
> +      <AdaptivityProvider>
@AliceSitedge памаги

2022-09-16 14:20 UTC, n-merkulova commented on src/templates/vk-mini-app/src/components/special/VKPanel/VKPanel.module.scss
> +  .background {
@AliceSitedge и тут тоже памаги

2022-09-16 14:31 UTC, n-merkulova commented on src/templates/vite-vk-mini-app/src/utils/setViewSettings.ts
> +export default () => setViewSettings(); // установить свои параметры
они уже есть внутри setViewSettings в @ktsstudio/mediaproject-vk

2022-09-19 10:37 UTC, AliceSitedge commented on src/templates/vite-vk-mini-app/src/components/special/VKPanel/VKPanel.module.scss
> +    padding: 0; // убираем отступы safe-area. убрать, если дизайн на vkui и отступы не помешают
Работает без important, видимо более специфичный селектор получается, но можно добавить на всякий

2022-09-19 11:26 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/App.tsx
> +      <AdaptivityProvider>
Да кстати, решение топ. Они там неправильно ее определяют, и десктопом считается только случай, когда `window.innerWidth` больше 1280... С планшетами кстати тоже беда, у них граничное значение 1024, поэтому было бы хорошо тоже как-то самим это определять, но это думаю уже другая задача

2022-09-19 11:51 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/components/special/VKPanel/VKPanel.module.scss
> +  .background {
Попробовала, сработало. Он добавляет паддинг на панели внутри эпика, но на них он уже переопределяется
<img width="315" alt="image" src="https://user-images.githubusercontent.com/43145208/191010968-8ea85051-2aae-4425-8fad-eb0369a84498.png">

2022-09-19 11:51 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/components/special/VKPanel/VKPanel.module.scss
> +  .background {
Правда нужно проверить, что в этом случае будет работать свайпбэк

2022-09-20 15:33 UTC, n-merkulova commented on src/templates/mediaproject/package.template.json
> +  "browserslist": {
по идее объявление уже есть в package.json, это равноценно файлу . browserslistrc и бабель тянет оттуда, но вообще для бабеля я переопределяю browserlits в зависимости от окружения - для дева это только последние версии некоторых браузеров, чтоб сборочка была быстрее, а для прода это поддержка и старых браузеров в том числе

2022-09-20 15:36 UTC, n-merkulova commented on src/templates/vk-mini-app/package.template.json
> +    "codestyle:fix": "prettier --write **/*.{js,ts,tsx,json,css,scss}",
вообще эта команда больше не нужна, потому что eslint теперь делает и работу prettier

2022-09-20 15:36 UTC, n-merkulova commented on src/templates/vk-mini-app/src/types/typings.ts
> -declare module '*.modules.scss' {
ну вроде проверила, работает без этого

2022-09-20 19:08 UTC, n-merkulova commented on src/templates/vk-mini-app/src/store/hooks/useLocalStore.ts
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
я постаралась по максимуму пофиксить использование этого свойства, но лучше его все же оставить. сам Дэн Абрамов не рекомендует его дизейблить...

2022-09-21 10:50 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/types/typings.ts
> -declare module '*.modules.scss' {
Аа, тогда нужно убрать это из других шаблонов. Видела, что в mediaproject просто на module.scss заменили

2022-09-21 11:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/package.template.json
> +    "codestyle:fix": "prettier --write **/*.{js,ts,tsx,json,css,scss}",
eslint иногда некрасивые штуки делает, например вот (это после прогона команды lint:fix), и потом сам же ругается
<img width="672" alt="image" src="https://user-images.githubusercontent.com/43145208/191487322-545ef3d0-1542-4931-8d0b-9acaba8ab835.png">
А после исправления вот такое
<img width="725" alt="image" src="https://user-images.githubusercontent.com/43145208/191487460-8e611ffe-286d-46b7-9d0d-74b8b6e0e496.png">

2022-10-04 10:21 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/types/typings.ts
> +declare module '*.module.scss' {
Кстати, а у файлов, которые находятся в папке types, не должно быть расширение .d.ts?

2022-10-04 10:21 UTC, AliceSitedge commented on src/templates/vite-vk-mini-app/src/components/Header/Header.tsx
> +import styles from './Header.module.scss';
В шаблоне с vite получается не будет работать синтаксис `styleName=""`?

2022-10-05 09:01 UTC, n-merkulova commented on src/templates/vite-vk-mini-app/src/components/Header/Header.tsx
> +import styles from './Header.module.scss';
пока что решили, что да

2023-01-20 15:50 UTC, wayvy commented on src/devMode.ts
> +      if (!err) {
`if (err) {`

2023-01-23 17:21 UTC, natalya-z commented on src/templates/vk-mini-app/package.template.json
> +    "@vkontakte/vkui": "^4.37.3",
Можно до последней 4ой обновить [4.41.0](https://www.npmjs.com/package/@vkontakte/vkui/v/4.41.0)

2023-01-23 17:34 UTC, AliceSitedge commented on src/templates/mediaproject/src/store/hooks/useAppLoad.ts
> +        rootStore.appState.setLoadedSuccessfully();
В mediaproject тут не нужно переход делать

2023-01-24 07:05 UTC, AliceSitedge commented on .gitignore
> +dev/
Это нужно, чтобы node_modules работал и на папках, и на файлах, потому что в папке шаблона во время режима разработки появляется симлинк на папку node_modules

2023-01-24 16:30 UTC, merged