Добавление работы с цветовой темой vkui
ktsstudio/create-mediaproject pull request #21
Opened 2022-09-20 13:00 UTC by AliceSitedge

- добавлена работа с цветовой схемой vkui
- добавлена конфигурация приложения в config/app

2022-09-20 19:11 UTC, natalya-z approved these changes

2022-09-20 19:11 UTC, natalya-z commented on src/templates/vk-mini-app/src/App.tsx
> -  // передать WebviewType.INTERNAL, если это внутреннее приложение
это точно стоит удалять?

2022-09-21 10:34 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/App.tsx
> -  // передать WebviewType.INTERNAL, если это внутреннее приложение
Здесь об этом теперь не нужно знать, приложение настраивается в конфиге

2022-09-24 08:30 UTC, n-merkulova requested changes

2022-09-24 08:30 UTC, n-merkulova commented on src/templates/vk-mini-app/src/utils/useWatchAppearance.ts
> +      bridge.subscribe(onConfigUpdate);
! я думаю, мб onConfigUpdate создавать прямо внутри useEffect? просто если в конфиге `withVkAppearance` будет `false`, тогда нет смысла создавать лишний коллбэк, пусть даже мемоизированный, а этот `useEffect` все равно вызывается только один раз

кстати еще такая мысль - я ведь сделала в новой версии функционал перезагрузки приложения в `AppStateStore` (вроде он так называется). мб можно в этом хуке обращаться к этому стору и при перезагрузке прила тоже цветовую схему обновлять?

2022-09-24 08:30 UTC, n-merkulova commented on src/templates/vk-mini-app/src/index.tsx
> +      <App initialAppearance={initialAppearance} />
! я понимаю, что это не очень, но придется всю ту же логику еще продублировать в шаблоне со сборкой на `vite`...

2022-09-24 08:30 UTC, n-merkulova commented on src/templates/vk-mini-app/src/index.tsx
> +  const config = app.withVkAppearance ? await bridge.send('VKWebAppGetConfig') : null;
! а это точно делается до отправки метода инициализации приложения, а не после? мб перенести это под `initializeVkApp`?

2022-09-24 08:30 UTC, n-merkulova commented on src/templates/vk-mini-app/src/index.tsx
> +  const initialAppearance = config?.appearance ?? 'light';
мб 'light' перенести в общий конфиг, как дефолтную цветовую схему?

2022-09-30 13:22 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/index.tsx
> +  const config = app.withVkAppearance ? await bridge.send('VKWebAppGetConfig') : null;
В доке написано такое
<img width="659" alt="image" src="https://user-images.githubusercontent.com/43145208/193278075-9d5b0fbf-a47c-42f1-b795-370b98d68cf1.png">
Плюс при вызове VKWebAppInit появляется окно приложения, которое изначально не знает текущую тему и в темной теме это окно белое. Если после этого еще будет задержка перед передачей темы в прил, будет заметен этот белый экран (актуально для десктопа, на мобиле он вроде не успевает появиться)

2022-10-05 07:43 UTC, n-merkulova approved these changes

2022-10-05 08:42 UTC, merged