2.1.0
ktsstudio/create-mediaproject pull request #27
Opened 2023-02-01 17:26 UTC by n-merkulova

- **vite-vk-mini-app**:
  - добавлен новый шаблон для вк мини аппа со сборкой на [vite](https://vitejs.dev/). структура проекта точно та же, что у шаблона vk-mini-app

2023-02-02 15:55 UTC, AliceSitedge requested changes

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/package.template.json
> +    "prepare": "husky install && rm -f .husky/pre-commit && husky add .husky/pre-commit \"yarn precommit\""
Такая команда будет падать. Я в других шаблонах оставляла тут `husky install`, и еще нужно проверить, что .husky/pre-commit исполняемый файл

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/src/pages/Home/Home.module.scss
> +@import "@ktsstudio/mediaproject-style/dist/mixins";
Может это в styles/mixins импортнуть?

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/src/store/globals/RootStore.ts
> +    this.appState.setLoadedSuccessfully();
Это нужно перенести в useAppLoad по аналогии с mediaproject

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/src/store/hooks/useAppLoad.ts
> +  }, [rootStore.appState.loading]);
И тут поменять на rootStore.appState.notLoaded

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/src/store/models/AppStateModel/AppStateModel.ts
> +      setState: action,
```suggestion
      setState: action.bound,
```
Блин надо было сначала все поправить, а потом выпиливать шаблон...

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/src/store/models/AppStateModel/AppStateModel.ts
> +  }
Тут еще метод reload я добавляла

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/vite.config.template.ts
> +      'SENTRY_AUTH_TOKEN'
Кстати это по-моему не нужно прокидывать в проект, и в других шаблонах тоже

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/src/components/special/ErrorBoundary/ErrorBoundary.tsx
> +          Произошла ошибка! Перезагрузите приложение или попробуйте позже
Можно тут тоже сделать компонент ErrorFallback с кнопкой для перезагрузки

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/vk-mini-app/package.template.json
> +    "@ktsstudio/mediaproject-vk": "^2.0.0",
mediaproject-vk 2 раза?

2023-02-02 15:55 UTC, AliceSitedge commented on src/templates/mediaproject-vite/vite.config.template.ts
> +          release: PACKAGE_JSON.version,
Может добавить сразу работу с сентри? Нужно только добавить условие на `IS_DEFAULT_BRANCH` и тут передать `process.env.CI_COMMIT_SHORT_SHA`

2023-02-07 06:33 UTC, AliceSitedge commented on CHANGELOG.md
> +# v2.1.0
И еще есть такое предложение в функции postProcess поменять порядок действий и installDeps вызывать в последнюю очередь. А то сейчас если эта команда падает, .gitignore не создается

2023-02-07 10:22 UTC, n-merkulova commented
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/36528697/217218398-cb726d08-32f0-47fb-bd0b-2f60c510e04d.png">

2023-03-17 16:14 UTC, AliceSitedge approved these changes

2023-03-23 10:03 UTC, merged