[*] routing
ktsstudio/create-mediaproject pull request #4
Opened 2021-11-09 17:49 UTC by n-merkulova

### v1.0.5
* vk-mini-app template
  * Modals in routing
  * SVGR plugin viebox options
  * Packages mediaproject-utils, mediaproject-vk versions upgrade

2021-11-10 08:22 UTC, natalya-z requested changes

2021-11-10 08:22 UTC, natalya-z commented on src/templates/vk-mini-app/src/config/routes/index.ts
> +export const routes: VKRoutesRecord = {
Надо явно записать, что у нас нельзя существовать панелям с одинаковыми названиями.  Потому что когда начинаешь разбираться с роутингом, не сразу понятно, почему там используется только панель, и нет никаких упоминаний о вьюшке.

2021-11-10 08:22 UTC, natalya-z commented on src/templates/vk-mini-app/src/pages/Main/Main.tsx
> +      <Button onClick={() => push({ panel: PanelEnum.onboarding })}>
Предлагаю добавить пример как пользоваться buildVKLocation в теге <a> например.
И как открывать модалки.
+ возможно вообще сами компоненты модалок и модальных страниц стоит добавить в шаблон

2021-11-10 08:22 UTC, natalya-z commented on src/templates/vk-mini-app/src/pages/Onboarding/Onboarding.modules.scss
> +  transform: translate(-50%, -50%);
Если библиотека со стилями разложена, то тут можно использовать миксины из нее

2021-11-10 08:22 UTC, natalya-z commented on src/templates/vk-mini-app/src/pages/Root/Root.tsx
> +    <VKRoot activeView={activeView}>
Добавить проверку на случай, если activeView=null, underfined. Ловили такие ошибки при переключении экранов с анимациями. 
UPD: если я правильно поняла, то в `useVKLocation` это уже проверяется

2021-11-10 08:22 UTC, natalya-z commented on src/templates/vk-mini-app/src/pages/Root/Root.tsx
> +      {Object.entries(views).map(([view, viewPanels]) => (
Показалось сложной логика:
- сначала возвращать из useVKViews массив [views]
- потом вытаскивать из него views: const [views] = useVKViews() в компонента App. Почему не делать это в Root?
- views views прокидывается в Root
- затем этот побитый жизнью объект снова прогоняется через Object.entries(views)

Мне потребовалось 15 минут чтобы раскрести эти преобразования. 
Можно в useVKViews отдавать Object.entries(views) например.

2021-11-10 08:22 UTC, natalya-z commented on src/templates/vk-mini-app/src/utils/router/utils/views/useVKViews.ts
> +// получение списка вьюшек со списком панелей для каждой
Это же объект вьюшек со списком панелей.
По описанию сначала кажется, что вернется массив

2021-11-10 08:22 UTC, natalya-z commented on src/templates/vk-mini-app/webpack.config.template.js
> +const buildStaticPath = (path) => `${isZip ? '' : `static/${path}`}`;
почему нельзя так?
`const buildStaticPath = (path) => (isZip ? '' : `static/${path}`);`

2021-11-10 09:32 UTC, wayvy commented on src/templates/vk-mini-app/src/config/routes/index.ts
> +export const routes: VKRoutesRecord = {
Мне казалось, что enumeration и так явно указывают на уникальные названия...

2021-11-10 09:52 UTC, andrewgul requested changes
gitignore бы добавить

2021-11-10 09:55 UTC, wayvy commented
> gitignore бы добавить

есть и в самом проекте и в шаблоне

2021-11-10 10:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/utils/router/utils/views/useVKViews.ts
> +  return [views];
Не поняла, зачем это упаковывается в массив, а потом распаковывается в `App`

2021-11-10 10:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/utils/router/utils/builders.ts
> +      canSwipeBack: canSwipeBack,
`{ modal, canSwipeBack }`

2021-11-10 10:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/utils/router/location/useVKLocation.ts
> +    route,
А зачем здесь может понадобиться `route`? Вью и панель уже возвращаются, а компонент для рендера в руте берется из конфига по панельке

2021-11-10 10:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/utils/router/location/useVKLocation.ts
> +    canSwipeBack: state?.canSwipeBack || true,
Если canSwipeBack будет false, значение перетрется на true
Лучше `state?.canSwipeBack ?? true`

2021-11-10 10:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/utils/router/history/useVKHistory.ts
> +    },
Можно это наверное вынести в отдельную функцию и передавать туда либо `push`, либо `replace`, чтобы не дублировать
И можно еще в `useCallback` обернуть эти функции, а то, насколько я понимаю, сейчас они создаются при каждом рендере

2021-11-10 10:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/utils/router/history/useVKHistory.ts
> +          panel: panel ? panel : activePanel,
`panel || activePanel`

2021-11-10 10:00 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/pages/Root/Root.tsx
> +  const handleAppReady = React.useCallback(async () => {
А зачем здесь `async`?

2021-11-12 10:37 UTC, n-merkulova commented on src/templates/vk-mini-app/src/config/routes/index.ts
> +export const routes: VKRoutesRecord = {
согласна с Сережей, сливаю

2021-11-12 10:39 UTC, n-merkulova commented on src/templates/vk-mini-app/src/pages/Main/Main.tsx
> +      <Button onClick={() => push({ panel: PanelEnum.onboarding })}>
для модалок есть, для тега добавила в Main

2021-11-12 11:30 UTC, n-merkulova commented on src/templates/vk-mini-app/src/pages/Root/Root.tsx
> +    <VKRoot activeView={activeView}>
да, там берется дефолтная панелька

2021-11-12 12:43 UTC, n-merkulova commented on src/templates/vk-mini-app/src/utils/router/location/useVKLocation.ts
> +    route,
ну вдруг надо узнать больше инфы о текущем роуте прямо внутри какого-то компонента - isFixed, name или что-то такое. например, в Достоевском у роута было имя и оно выводилось в шапке

2021-11-21 18:43 UTC, natalya-z approved these changes

2021-11-22 09:12 UTC, AliceSitedge approved these changes

2021-11-22 09:12 UTC, AliceSitedge commented on src/templates/vk-mini-app/README.template.md
> +На старте в [index.tsx](src/index.tsx) вызывает [VKWebAppInit](https://vk.com/dev/vkbridge/vkwebappinit) и инициализирует [параметры запуска vk-mini-app](https://vk.com/dev/vk_apps_docs3?f=6.%2B%D0%9
Тут часть ссылок невалидные

2021-11-22 09:12 UTC, AliceSitedge commented on src/templates/vk-mini-app/README.template.md
> +URL'ы для страниц создаются в следующем формате: `/view/panel`. Вью и панели приложения хранятся в [конфиге](src/config/routes) в виде enum. Так же к проекту подключен [MobX](https://mobx.js.org/), к
И тут

2021-11-22 09:46 UTC, wayvy approved these changes
👍

2021-11-22 09:46 UTC, wayvy commented on src/templates/vk-mini-app/src/config/routes/types.ts
> +import { ViewEnum, PanelEnum } from './index';
Может в следующией итерации сделать просто Views, Panels?

2021-11-23 12:59 UTC, andrewgul approved these changes

2021-11-23 13:16 UTC, merged