1.2.0: шаблон mediaproject
ktsstudio/create-mediaproject pull request #6
Opened 2022-01-13 09:30 UTC by AliceSitedge

2022-01-13 10:21 UTC, natalya-z commented on src/templates/mediaproject/src/pages/Home/Home.modules.scss
> +    transition: color 0.2s ease;
можно использовать тут миксин из пакета со стилями

2022-01-13 11:49 UTC, natalya-z requested changes

2022-01-13 11:49 UTC, natalya-z commented on src/templates/mediaproject/package.template.json
> +    "@babel/core": "^7.16.5",
@babel/polyfill можно убрать
тут написано https://babeljs.io/docs/en/babel-polyfill , что он в core-js/stable есть

2022-01-13 11:49 UTC, natalya-z commented on src/templates/mediaproject/package.template.json
> +    "@babel/cli": "^7.16.0",
можно убрать, если не используется

2022-01-13 15:36 UTC, natalya-z commented on src/templates/mediaproject/babel.config.js
> +          'generateScopedName': isProd ? '[hash:base64]' : '[path][name]__[local]',
Можно писать без кавычек: generateScopedName, webpackHotModuleReloading и тд

2022-01-13 15:39 UTC, natalya-z commented on src/templates/mediaproject/babel.config.js
> +      !isProd && 'react-refresh/babel',
не работает( в консоли есть предупреждение при запуске
![Uploading Снимок экрана 2022-01-13 в 18.30.12.png…]()

2022-01-13 15:55 UTC, natalya-z commented on src/templates/mediaproject/webpack.config.template.js
> +    historyApiFallback: true,
помогло добавить webSocketServer: false, от ошибок в консоли:
<img width="599" alt="Снимок экрана 2022-01-13 в 16 49 04" src="https://user-images.githubusercontent.com/63305213/149363765-5043e165-8e16-4855-bf50-48ddbaaa9973.png">

2022-01-14 10:47 UTC, wayvy approved these changes

2022-01-14 10:47 UTC, wayvy commented on src/templates/mediaproject/src/index.tsx
> +  markup(true).init();
withCheckMobile По умолчанию true.

2022-01-14 10:47 UTC, wayvy commented on src/templates/mediaproject/src/index.template.html
> +  <meta property="og:image" content="./static/img/share/share.jpg" />
Думаю, стоит добавить плейсхолдер без чужих логотипов

2022-01-14 12:31 UTC, AliceSitedge commented on src/templates/mediaproject/package.template.json
> +    "husky": "^7.0.4",
Вынести в readme требования к версии гита и ноды

2022-01-17 15:54 UTC, n-merkulova requested changes

2022-01-17 15:54 UTC, n-merkulova commented on package.json
> +  "version": "1.0.6",
1.1.0 уже, получается

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/.gitlab-ci.template.yml
> +  DEV_API_DOMAIN: <%= projectName %>.kube1.ktsdev2.ru
кстати можно делать вложенность меньше и не писать поддомен kube1

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/package.template.json
> +    "@ktsstudio/mediaproject-utils": "^3.0.0",
можно обновить версии библиотек ktsstudio

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/config/urls.ts
> +import { UrlConfigType } from 'types/urls';
да, наверно стоит в utils добавить

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/index.template.html
> +    href="./static/img/favicon/apple-touch-icon.png"
oh my, так это из форт-боярда... на самом деле можно здесь оставить просто одну фавиконку, не париться с кучей разных и просто нарисовать какую-то свою дефолтную, но не брать из форт-боярда

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/static/img/favicon/site.webmanifest
> +            "src": "/android-chrome-192x192.png",
короче мне кажется, что дрочь с фавиконкой не оправдана, потому что все эти файлики отлично генерит онлайн генератор веб-фавиконок, вот

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/index.template.html
> +  <meta property="og:image" content="./static/img/share/share.jpg" />
да, здесь либо свое что-то нарисовать, либо вообще не делать картинку. можно оставить TODO

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/store/RootStore.ts
> +export class RootStore {}
можно будет тут использовать mediaproject-stores

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/styles/colors.scss
> +$white: #fff;
не знаю, насколько нужно столько цветов хранить, плюс в scss-файле, когда у нас проект на styled-components

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/styles/fonts/Montserrat/stylesheet.scss
> +  font-family: 'Montserrat';
думаю, не надо добавлять кастомные шрифты, ведь все равно их удалять и потом на их место ставить новые

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/types/typings.d.ts
> +declare module '*.jpg';
gif лучше убрать, а вот jpeg можно добавить

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/src/types/window.d.ts
> +    is_dev: boolean;
вот это можно убрать, если обновить версию утилит

2022-01-17 15:54 UTC, n-merkulova commented on src/templates/mediaproject/webpack.config.template.js
> +        from: path.join(srcPath, 'static', 'img'),
не знаю, насколько нужна папка static - в форт боярде она была для шеринга и для картинки в мета-данных. наверное, можно оставить, только убрать еще img внутри

2022-01-17 15:58 UTC, n-merkulova commented on src/templates/mediaproject/webpack.config.template.js
> +    historyApiFallback: true,
хм, а с какой версией ноды ты смотрела? у меня ничего похожего нет, вроде только если стопануть сервер и пытаться что-то еще запросить

2022-01-17 16:01 UTC, n-merkulova commented on src/templates/mediaproject/package.template.json
> +    "lint-fix": "eslint --fix src",
вот эта команда точно работает на любом уровне вложенности? мне казалось, что надо добавлять src/**/*.{тут расширения файлов}

2022-01-17 16:03 UTC, n-merkulova commented on src/templates/mediaproject/package.template.json
> +    "codestyle-fix": "prettier --write **/*.{js,ts,tsx,json,scss}",
это точно не работает для подкатегорий в src, мб поможет src/**/*.*?

2022-01-18 14:14 UTC, dewolixgit commented on src/templates/vk-mini-app/src/pages/Root/Root.tsx
>  import '../../styles/styles.scss';
а почему импорт относительно расположения файла, а не использование алиаса? у самого были проблемы с такой строкой, но как-то не разобрался, отчего алиас не работает..

2022-03-14 08:52 UTC, AliceSitedge commented on src/templates/mediaproject/webpack.config.template.js
> +      utils: path.join(srcPath, 'utils'),
Думаю не нужна, она нужна только для картинок для шеринга и фавиконок

2022-03-14 08:56 UTC, AliceSitedge commented on src/templates/mediaproject/src/styles/fonts/Montserrat/stylesheet.scss
> +  font-family: 'Montserrat';
Оставила только те, что используются. Думаю, какие-то нужно оставить, чтобы был пример подключения

2022-03-14 09:06 UTC, AliceSitedge commented on src/templates/mediaproject/package.template.json
> +    "lint-fix": "eslint --fix src",
Проверила, работает на любом уровне вложенности

2022-03-14 11:25 UTC, AliceSitedge commented on src/templates/mediaproject/babel.config.js
> +      !isProd && 'react-refresh/babel',
Это не работает, если включить webSocketServer: false... Убрала это в итоге

2022-03-14 11:26 UTC, AliceSitedge commented on src/templates/mediaproject/webpack.config.template.js
> +    historyApiFallback: true,
Короче если это добавить, hot reload не будет работать

2022-03-14 11:54 UTC, AliceSitedge commented on src/templates/vk-mini-app/src/pages/Root/Root.tsx
>  import '../../styles/styles.scss';
Хз, если честно..

2022-03-21 10:57 UTC, merged